- name: MYSql setup
  hosts: all
  become: yes
  tasks:
   - name: Install MYSQL server
     ansible.builtin.dnf:
      name: mysql-server
      state: latest

   - name : restart servers
     ansible.builtin.systemd_service:
       name: mysqld
       state: started
       enabled: yes
   - name: "Installing pip dependencies"
     pip:
       name: MySQL-python
       extra_args: --index=https://pypi.python.org/pypi/
       version: 1.2.3

   - name :
     community.mysql.mysql_user:
       state: present
       name: root
       password: ExpenseApp@1



