- name: MYSql setup
  hosts: all
  become: yes
  tasks:
   - name: Install MYSQL server
     ansible.builtin.dnf:
      name: mysql-server
      state: latest

   - name : restart servers
     ansible.builtin.systemd_service:
       name: mysqld
       state: started
       enabled: yes

   - name: "Installing pip dependencies"
     pip:
       name: pymysql
       state: present

   - name :
     community.mysql.mysql_user:
       state: present
       name: root
       password: ExpenseApp@1



