- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: copy nginx configuration
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: imporing thr prerquisite using common file
  ansible.builtin.import_role:
    name: Common
    tasks_from: Pre

- name: start nginx sever
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes
