- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: copy nginx configuration
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: importing thr prerquisite using common file
  ansible.builtin.import_role:
    name: common
    tasks_from: main

- name: start nginx sever
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes
